// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Data;

namespace Projeto.Migrations
{
    [DbContext(typeof(ProjetoContext))]
    [Migration("20220702221035_Primeira")]
    partial class Primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<int>("Lvl");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int?>("orderId");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Projeto.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Moment");

                    b.Property<double>("Total");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Projeto.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderId");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Projeto.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Bytes");

                    b.Property<string>("DescriptionF");

                    b.Property<string>("FileExtension");

                    b.Property<int>("ProductId");

                    b.Property<decimal>("Size");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Projeto.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionP")
                        .IsRequired();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<DateTime>("ManufactoringDate");

                    b.Property<decimal>("Price");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Projeto.Models.Client", b =>
                {
                    b.HasOne("Projeto.Models.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderId");
                });

            modelBuilder.Entity("Projeto.Models.OrderItem", b =>
                {
                    b.HasOne("Projeto.Models.Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Projeto.Models.Photo", b =>
                {
                    b.HasOne("Projeto.Models.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
